// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: head.proto

package hc.head;

public final class ProtoHead {
  private ProtoHead() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HeadOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint32 srcID = 1;
    /**
     * <code>required uint32 srcID = 1;</code>
     */
    boolean hasSrcID();
    /**
     * <code>required uint32 srcID = 1;</code>
     */
    int getSrcID();

    // required uint32 desID = 2;
    /**
     * <code>required uint32 desID = 2;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    boolean hasDesID();
    /**
     * <code>required uint32 desID = 2;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    int getDesID();

    // required .head.Head.ProtoType type = 3;
    /**
     * <code>required .head.Head.ProtoType type = 3;</code>
     */
    boolean hasType();
    /**
     * <code>required .head.Head.ProtoType type = 3;</code>
     */
    hc.head.ProtoHead.Head.ProtoType getType();

    // required uint32 protoID = 4;
    /**
     * <code>required uint32 protoID = 4;</code>
     */
    boolean hasProtoID();
    /**
     * <code>required uint32 protoID = 4;</code>
     */
    int getProtoID();
  }
  /**
   * Protobuf type {@code head.Head}
   */
  public static final class Head extends
      com.google.protobuf.GeneratedMessage
      implements HeadOrBuilder {
    // Use Head.newBuilder() to construct.
    private Head(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Head(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Head defaultInstance;
    public static Head getDefaultInstance() {
      return defaultInstance;
    }

    public Head getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Head(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              srcID_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              desID_ = input.readUInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              hc.head.ProtoHead.Head.ProtoType value = hc.head.ProtoHead.Head.ProtoType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                type_ = value;
              }
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              protoID_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hc.head.ProtoHead.internal_static_head_Head_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hc.head.ProtoHead.internal_static_head_Head_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hc.head.ProtoHead.Head.class, hc.head.ProtoHead.Head.Builder.class);
    }

    public static com.google.protobuf.Parser<Head> PARSER =
        new com.google.protobuf.AbstractParser<Head>() {
      public Head parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Head(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Head> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code head.Head.ProtoType}
     */
    public enum ProtoType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PROTOBUF = 0;</code>
       */
      PROTOBUF(0, 0),
      ;

      /**
       * <code>PROTOBUF = 0;</code>
       */
      public static final int PROTOBUF_VALUE = 0;


      public final int getNumber() { return value; }

      public static ProtoType valueOf(int value) {
        switch (value) {
          case 0: return PROTOBUF;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ProtoType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ProtoType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ProtoType>() {
              public ProtoType findValueByNumber(int number) {
                return ProtoType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return hc.head.ProtoHead.Head.getDescriptor().getEnumTypes().get(0);
      }

      private static final ProtoType[] VALUES = values();

      public static ProtoType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ProtoType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:head.Head.ProtoType)
    }

    private int bitField0_;
    // required uint32 srcID = 1;
    public static final int SRCID_FIELD_NUMBER = 1;
    private int srcID_;
    /**
     * <code>required uint32 srcID = 1;</code>
     */
    public boolean hasSrcID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 srcID = 1;</code>
     */
    public int getSrcID() {
      return srcID_;
    }

    // required uint32 desID = 2;
    public static final int DESID_FIELD_NUMBER = 2;
    private int desID_;
    /**
     * <code>required uint32 desID = 2;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    public boolean hasDesID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 desID = 2;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    public int getDesID() {
      return desID_;
    }

    // required .head.Head.ProtoType type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private hc.head.ProtoHead.Head.ProtoType type_;
    /**
     * <code>required .head.Head.ProtoType type = 3;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .head.Head.ProtoType type = 3;</code>
     */
    public hc.head.ProtoHead.Head.ProtoType getType() {
      return type_;
    }

    // required uint32 protoID = 4;
    public static final int PROTOID_FIELD_NUMBER = 4;
    private int protoID_;
    /**
     * <code>required uint32 protoID = 4;</code>
     */
    public boolean hasProtoID() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint32 protoID = 4;</code>
     */
    public int getProtoID() {
      return protoID_;
    }

    private void initFields() {
      srcID_ = 0;
      desID_ = 0;
      type_ = hc.head.ProtoHead.Head.ProtoType.PROTOBUF;
      protoID_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSrcID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDesID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProtoID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, srcID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, desID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, protoID_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, srcID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, desID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, protoID_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static hc.head.ProtoHead.Head parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hc.head.ProtoHead.Head parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hc.head.ProtoHead.Head parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hc.head.ProtoHead.Head parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hc.head.ProtoHead.Head parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hc.head.ProtoHead.Head parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static hc.head.ProtoHead.Head parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static hc.head.ProtoHead.Head parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static hc.head.ProtoHead.Head parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hc.head.ProtoHead.Head parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(hc.head.ProtoHead.Head prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code head.Head}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements hc.head.ProtoHead.HeadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hc.head.ProtoHead.internal_static_head_Head_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hc.head.ProtoHead.internal_static_head_Head_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hc.head.ProtoHead.Head.class, hc.head.ProtoHead.Head.Builder.class);
      }

      // Construct using hc.head.ProtoHead.Head.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        srcID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        desID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = hc.head.ProtoHead.Head.ProtoType.PROTOBUF;
        bitField0_ = (bitField0_ & ~0x00000004);
        protoID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hc.head.ProtoHead.internal_static_head_Head_descriptor;
      }

      public hc.head.ProtoHead.Head getDefaultInstanceForType() {
        return hc.head.ProtoHead.Head.getDefaultInstance();
      }

      public hc.head.ProtoHead.Head build() {
        hc.head.ProtoHead.Head result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public hc.head.ProtoHead.Head buildPartial() {
        hc.head.ProtoHead.Head result = new hc.head.ProtoHead.Head(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.srcID_ = srcID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.desID_ = desID_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.protoID_ = protoID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hc.head.ProtoHead.Head) {
          return mergeFrom((hc.head.ProtoHead.Head)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hc.head.ProtoHead.Head other) {
        if (other == hc.head.ProtoHead.Head.getDefaultInstance()) return this;
        if (other.hasSrcID()) {
          setSrcID(other.getSrcID());
        }
        if (other.hasDesID()) {
          setDesID(other.getDesID());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasProtoID()) {
          setProtoID(other.getProtoID());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSrcID()) {
          
          return false;
        }
        if (!hasDesID()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasProtoID()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hc.head.ProtoHead.Head parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hc.head.ProtoHead.Head) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 srcID = 1;
      private int srcID_ ;
      /**
       * <code>required uint32 srcID = 1;</code>
       */
      public boolean hasSrcID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 srcID = 1;</code>
       */
      public int getSrcID() {
        return srcID_;
      }
      /**
       * <code>required uint32 srcID = 1;</code>
       */
      public Builder setSrcID(int value) {
        bitField0_ |= 0x00000001;
        srcID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 srcID = 1;</code>
       */
      public Builder clearSrcID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        srcID_ = 0;
        onChanged();
        return this;
      }

      // required uint32 desID = 2;
      private int desID_ ;
      /**
       * <code>required uint32 desID = 2;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public boolean hasDesID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 desID = 2;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public int getDesID() {
        return desID_;
      }
      /**
       * <code>required uint32 desID = 2;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public Builder setDesID(int value) {
        bitField0_ |= 0x00000002;
        desID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 desID = 2;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public Builder clearDesID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        desID_ = 0;
        onChanged();
        return this;
      }

      // required .head.Head.ProtoType type = 3;
      private hc.head.ProtoHead.Head.ProtoType type_ = hc.head.ProtoHead.Head.ProtoType.PROTOBUF;
      /**
       * <code>required .head.Head.ProtoType type = 3;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .head.Head.ProtoType type = 3;</code>
       */
      public hc.head.ProtoHead.Head.ProtoType getType() {
        return type_;
      }
      /**
       * <code>required .head.Head.ProtoType type = 3;</code>
       */
      public Builder setType(hc.head.ProtoHead.Head.ProtoType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .head.Head.ProtoType type = 3;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = hc.head.ProtoHead.Head.ProtoType.PROTOBUF;
        onChanged();
        return this;
      }

      // required uint32 protoID = 4;
      private int protoID_ ;
      /**
       * <code>required uint32 protoID = 4;</code>
       */
      public boolean hasProtoID() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint32 protoID = 4;</code>
       */
      public int getProtoID() {
        return protoID_;
      }
      /**
       * <code>required uint32 protoID = 4;</code>
       */
      public Builder setProtoID(int value) {
        bitField0_ |= 0x00000008;
        protoID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 protoID = 4;</code>
       */
      public Builder clearProtoID() {
        bitField0_ = (bitField0_ & ~0x00000008);
        protoID_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:head.Head)
    }

    static {
      defaultInstance = new Head(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:head.Head)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_head_Head_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_head_Head_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nhead.proto\022\004head\"t\n\004Head\022\r\n\005srcID\030\001 \002(" +
      "\r\022\r\n\005desID\030\002 \002(\r\022\"\n\004type\030\003 \002(\0162\024.head.He" +
      "ad.ProtoType\022\017\n\007protoID\030\004 \002(\r\"\031\n\tProtoTy" +
      "pe\022\014\n\010PROTOBUF\020\000B\024\n\007hc.headB\tProtoHead"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_head_Head_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_head_Head_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_head_Head_descriptor,
              new java.lang.String[] { "SrcID", "DesID", "Type", "ProtoID", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
