// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package hc.login;

public final class PessCheck {
  private PessCheck() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoginReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string accountName = 1;
    /**
     * <code>required string accountName = 1;</code>
     */
    boolean hasAccountName();
    /**
     * <code>required string accountName = 1;</code>
     */
    java.lang.String getAccountName();
    /**
     * <code>required string accountName = 1;</code>
     */
    com.google.protobuf.ByteString
        getAccountNameBytes();
  }
  /**
   * Protobuf type {@code login.LoginReq}
   *
   * <pre>
   *11
   * </pre>
   */
  public static final class LoginReq extends
      com.google.protobuf.GeneratedMessage
      implements LoginReqOrBuilder {
    // Use LoginReq.newBuilder() to construct.
    private LoginReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginReq defaultInstance;
    public static LoginReq getDefaultInstance() {
      return defaultInstance;
    }

    public LoginReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              accountName_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hc.login.PessCheck.internal_static_login_LoginReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hc.login.PessCheck.internal_static_login_LoginReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hc.login.PessCheck.LoginReq.class, hc.login.PessCheck.LoginReq.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginReq> PARSER =
        new com.google.protobuf.AbstractParser<LoginReq>() {
      public LoginReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string accountName = 1;
    public static final int ACCOUNTNAME_FIELD_NUMBER = 1;
    private java.lang.Object accountName_;
    /**
     * <code>required string accountName = 1;</code>
     */
    public boolean hasAccountName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string accountName = 1;</code>
     */
    public java.lang.String getAccountName() {
      java.lang.Object ref = accountName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          accountName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string accountName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAccountNameBytes() {
      java.lang.Object ref = accountName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      accountName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAccountName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAccountNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAccountNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static hc.login.PessCheck.LoginReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hc.login.PessCheck.LoginReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hc.login.PessCheck.LoginReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hc.login.PessCheck.LoginReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hc.login.PessCheck.LoginReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hc.login.PessCheck.LoginReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static hc.login.PessCheck.LoginReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static hc.login.PessCheck.LoginReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static hc.login.PessCheck.LoginReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hc.login.PessCheck.LoginReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(hc.login.PessCheck.LoginReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code login.LoginReq}
     *
     * <pre>
     *11
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements hc.login.PessCheck.LoginReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hc.login.PessCheck.internal_static_login_LoginReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hc.login.PessCheck.internal_static_login_LoginReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hc.login.PessCheck.LoginReq.class, hc.login.PessCheck.LoginReq.Builder.class);
      }

      // Construct using hc.login.PessCheck.LoginReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        accountName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hc.login.PessCheck.internal_static_login_LoginReq_descriptor;
      }

      public hc.login.PessCheck.LoginReq getDefaultInstanceForType() {
        return hc.login.PessCheck.LoginReq.getDefaultInstance();
      }

      public hc.login.PessCheck.LoginReq build() {
        hc.login.PessCheck.LoginReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public hc.login.PessCheck.LoginReq buildPartial() {
        hc.login.PessCheck.LoginReq result = new hc.login.PessCheck.LoginReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.accountName_ = accountName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hc.login.PessCheck.LoginReq) {
          return mergeFrom((hc.login.PessCheck.LoginReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hc.login.PessCheck.LoginReq other) {
        if (other == hc.login.PessCheck.LoginReq.getDefaultInstance()) return this;
        if (other.hasAccountName()) {
          bitField0_ |= 0x00000001;
          accountName_ = other.accountName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAccountName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hc.login.PessCheck.LoginReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hc.login.PessCheck.LoginReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string accountName = 1;
      private java.lang.Object accountName_ = "";
      /**
       * <code>required string accountName = 1;</code>
       */
      public boolean hasAccountName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string accountName = 1;</code>
       */
      public java.lang.String getAccountName() {
        java.lang.Object ref = accountName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          accountName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string accountName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAccountNameBytes() {
        java.lang.Object ref = accountName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accountName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string accountName = 1;</code>
       */
      public Builder setAccountName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        accountName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string accountName = 1;</code>
       */
      public Builder clearAccountName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        accountName_ = getDefaultInstance().getAccountName();
        onChanged();
        return this;
      }
      /**
       * <code>required string accountName = 1;</code>
       */
      public Builder setAccountNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        accountName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:login.LoginReq)
    }

    static {
      defaultInstance = new LoginReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:login.LoginReq)
  }

  public interface LoginRspOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 result = 1;
    /**
     * <code>required int32 result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>required int32 result = 1;</code>
     */
    int getResult();

    // required int64 userID = 2;
    /**
     * <code>required int64 userID = 2;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    boolean hasUserID();
    /**
     * <code>required int64 userID = 2;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    long getUserID();
  }
  /**
   * Protobuf type {@code login.LoginRsp}
   *
   * <pre>
   *14
   * </pre>
   */
  public static final class LoginRsp extends
      com.google.protobuf.GeneratedMessage
      implements LoginRspOrBuilder {
    // Use LoginRsp.newBuilder() to construct.
    private LoginRsp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginRsp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginRsp defaultInstance;
    public static LoginRsp getDefaultInstance() {
      return defaultInstance;
    }

    public LoginRsp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              userID_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hc.login.PessCheck.internal_static_login_LoginRsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hc.login.PessCheck.internal_static_login_LoginRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hc.login.PessCheck.LoginRsp.class, hc.login.PessCheck.LoginRsp.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginRsp> PARSER =
        new com.google.protobuf.AbstractParser<LoginRsp>() {
      public LoginRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginRsp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginRsp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>required int32 result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 result = 1;</code>
     */
    public int getResult() {
      return result_;
    }

    // required int64 userID = 2;
    public static final int USERID_FIELD_NUMBER = 2;
    private long userID_;
    /**
     * <code>required int64 userID = 2;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    public boolean hasUserID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 userID = 2;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    public long getUserID() {
      return userID_;
    }

    private void initFields() {
      result_ = 0;
      userID_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, userID_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, userID_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static hc.login.PessCheck.LoginRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hc.login.PessCheck.LoginRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hc.login.PessCheck.LoginRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hc.login.PessCheck.LoginRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hc.login.PessCheck.LoginRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hc.login.PessCheck.LoginRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static hc.login.PessCheck.LoginRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static hc.login.PessCheck.LoginRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static hc.login.PessCheck.LoginRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hc.login.PessCheck.LoginRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(hc.login.PessCheck.LoginRsp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code login.LoginRsp}
     *
     * <pre>
     *14
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements hc.login.PessCheck.LoginRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hc.login.PessCheck.internal_static_login_LoginRsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hc.login.PessCheck.internal_static_login_LoginRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hc.login.PessCheck.LoginRsp.class, hc.login.PessCheck.LoginRsp.Builder.class);
      }

      // Construct using hc.login.PessCheck.LoginRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        userID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hc.login.PessCheck.internal_static_login_LoginRsp_descriptor;
      }

      public hc.login.PessCheck.LoginRsp getDefaultInstanceForType() {
        return hc.login.PessCheck.LoginRsp.getDefaultInstance();
      }

      public hc.login.PessCheck.LoginRsp build() {
        hc.login.PessCheck.LoginRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public hc.login.PessCheck.LoginRsp buildPartial() {
        hc.login.PessCheck.LoginRsp result = new hc.login.PessCheck.LoginRsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userID_ = userID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hc.login.PessCheck.LoginRsp) {
          return mergeFrom((hc.login.PessCheck.LoginRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hc.login.PessCheck.LoginRsp other) {
        if (other == hc.login.PessCheck.LoginRsp.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasUserID()) {
          setUserID(other.getUserID());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        if (!hasUserID()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hc.login.PessCheck.LoginRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hc.login.PessCheck.LoginRsp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 result = 1;
      private int result_ ;
      /**
       * <code>required int32 result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 result = 1;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>required int32 result = 1;</code>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 result = 1;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }

      // required int64 userID = 2;
      private long userID_ ;
      /**
       * <code>required int64 userID = 2;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public boolean hasUserID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 userID = 2;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public long getUserID() {
        return userID_;
      }
      /**
       * <code>required int64 userID = 2;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public Builder setUserID(long value) {
        bitField0_ |= 0x00000002;
        userID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 userID = 2;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public Builder clearUserID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userID_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:login.LoginRsp)
    }

    static {
      defaultInstance = new LoginRsp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:login.LoginRsp)
  }

  public interface LoginPessReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string accountName = 1;
    /**
     * <code>required string accountName = 1;</code>
     */
    boolean hasAccountName();
    /**
     * <code>required string accountName = 1;</code>
     */
    java.lang.String getAccountName();
    /**
     * <code>required string accountName = 1;</code>
     */
    com.google.protobuf.ByteString
        getAccountNameBytes();

    // required int64 sessionID = 2;
    /**
     * <code>required int64 sessionID = 2;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    boolean hasSessionID();
    /**
     * <code>required int64 sessionID = 2;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    long getSessionID();
  }
  /**
   * Protobuf type {@code login.LoginPessReq}
   *
   * <pre>
   *12
   * </pre>
   */
  public static final class LoginPessReq extends
      com.google.protobuf.GeneratedMessage
      implements LoginPessReqOrBuilder {
    // Use LoginPessReq.newBuilder() to construct.
    private LoginPessReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginPessReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginPessReq defaultInstance;
    public static LoginPessReq getDefaultInstance() {
      return defaultInstance;
    }

    public LoginPessReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginPessReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              accountName_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sessionID_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hc.login.PessCheck.internal_static_login_LoginPessReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hc.login.PessCheck.internal_static_login_LoginPessReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hc.login.PessCheck.LoginPessReq.class, hc.login.PessCheck.LoginPessReq.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginPessReq> PARSER =
        new com.google.protobuf.AbstractParser<LoginPessReq>() {
      public LoginPessReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginPessReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginPessReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string accountName = 1;
    public static final int ACCOUNTNAME_FIELD_NUMBER = 1;
    private java.lang.Object accountName_;
    /**
     * <code>required string accountName = 1;</code>
     */
    public boolean hasAccountName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string accountName = 1;</code>
     */
    public java.lang.String getAccountName() {
      java.lang.Object ref = accountName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          accountName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string accountName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAccountNameBytes() {
      java.lang.Object ref = accountName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 sessionID = 2;
    public static final int SESSIONID_FIELD_NUMBER = 2;
    private long sessionID_;
    /**
     * <code>required int64 sessionID = 2;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    public boolean hasSessionID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 sessionID = 2;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    public long getSessionID() {
      return sessionID_;
    }

    private void initFields() {
      accountName_ = "";
      sessionID_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAccountName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSessionID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAccountNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, sessionID_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAccountNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, sessionID_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static hc.login.PessCheck.LoginPessReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hc.login.PessCheck.LoginPessReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hc.login.PessCheck.LoginPessReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hc.login.PessCheck.LoginPessReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hc.login.PessCheck.LoginPessReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hc.login.PessCheck.LoginPessReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static hc.login.PessCheck.LoginPessReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static hc.login.PessCheck.LoginPessReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static hc.login.PessCheck.LoginPessReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hc.login.PessCheck.LoginPessReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(hc.login.PessCheck.LoginPessReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code login.LoginPessReq}
     *
     * <pre>
     *12
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements hc.login.PessCheck.LoginPessReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hc.login.PessCheck.internal_static_login_LoginPessReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hc.login.PessCheck.internal_static_login_LoginPessReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hc.login.PessCheck.LoginPessReq.class, hc.login.PessCheck.LoginPessReq.Builder.class);
      }

      // Construct using hc.login.PessCheck.LoginPessReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        accountName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sessionID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hc.login.PessCheck.internal_static_login_LoginPessReq_descriptor;
      }

      public hc.login.PessCheck.LoginPessReq getDefaultInstanceForType() {
        return hc.login.PessCheck.LoginPessReq.getDefaultInstance();
      }

      public hc.login.PessCheck.LoginPessReq build() {
        hc.login.PessCheck.LoginPessReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public hc.login.PessCheck.LoginPessReq buildPartial() {
        hc.login.PessCheck.LoginPessReq result = new hc.login.PessCheck.LoginPessReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.accountName_ = accountName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sessionID_ = sessionID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hc.login.PessCheck.LoginPessReq) {
          return mergeFrom((hc.login.PessCheck.LoginPessReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hc.login.PessCheck.LoginPessReq other) {
        if (other == hc.login.PessCheck.LoginPessReq.getDefaultInstance()) return this;
        if (other.hasAccountName()) {
          bitField0_ |= 0x00000001;
          accountName_ = other.accountName_;
          onChanged();
        }
        if (other.hasSessionID()) {
          setSessionID(other.getSessionID());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAccountName()) {
          
          return false;
        }
        if (!hasSessionID()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hc.login.PessCheck.LoginPessReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hc.login.PessCheck.LoginPessReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string accountName = 1;
      private java.lang.Object accountName_ = "";
      /**
       * <code>required string accountName = 1;</code>
       */
      public boolean hasAccountName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string accountName = 1;</code>
       */
      public java.lang.String getAccountName() {
        java.lang.Object ref = accountName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          accountName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string accountName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAccountNameBytes() {
        java.lang.Object ref = accountName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accountName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string accountName = 1;</code>
       */
      public Builder setAccountName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        accountName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string accountName = 1;</code>
       */
      public Builder clearAccountName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        accountName_ = getDefaultInstance().getAccountName();
        onChanged();
        return this;
      }
      /**
       * <code>required string accountName = 1;</code>
       */
      public Builder setAccountNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        accountName_ = value;
        onChanged();
        return this;
      }

      // required int64 sessionID = 2;
      private long sessionID_ ;
      /**
       * <code>required int64 sessionID = 2;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public boolean hasSessionID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 sessionID = 2;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public long getSessionID() {
        return sessionID_;
      }
      /**
       * <code>required int64 sessionID = 2;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public Builder setSessionID(long value) {
        bitField0_ |= 0x00000002;
        sessionID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 sessionID = 2;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public Builder clearSessionID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionID_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:login.LoginPessReq)
    }

    static {
      defaultInstance = new LoginPessReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:login.LoginPessReq)
  }

  public interface LoginPessRspOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 result = 1;
    /**
     * <code>required int32 result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>required int32 result = 1;</code>
     */
    int getResult();

    // required int64 userID = 2;
    /**
     * <code>required int64 userID = 2;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    boolean hasUserID();
    /**
     * <code>required int64 userID = 2;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    long getUserID();

    // required int64 sessionID = 3;
    /**
     * <code>required int64 sessionID = 3;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    boolean hasSessionID();
    /**
     * <code>required int64 sessionID = 3;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    long getSessionID();
  }
  /**
   * Protobuf type {@code login.LoginPessRsp}
   *
   * <pre>
   *13
   * </pre>
   */
  public static final class LoginPessRsp extends
      com.google.protobuf.GeneratedMessage
      implements LoginPessRspOrBuilder {
    // Use LoginPessRsp.newBuilder() to construct.
    private LoginPessRsp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginPessRsp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginPessRsp defaultInstance;
    public static LoginPessRsp getDefaultInstance() {
      return defaultInstance;
    }

    public LoginPessRsp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginPessRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              userID_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              sessionID_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hc.login.PessCheck.internal_static_login_LoginPessRsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hc.login.PessCheck.internal_static_login_LoginPessRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hc.login.PessCheck.LoginPessRsp.class, hc.login.PessCheck.LoginPessRsp.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginPessRsp> PARSER =
        new com.google.protobuf.AbstractParser<LoginPessRsp>() {
      public LoginPessRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginPessRsp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginPessRsp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>required int32 result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 result = 1;</code>
     */
    public int getResult() {
      return result_;
    }

    // required int64 userID = 2;
    public static final int USERID_FIELD_NUMBER = 2;
    private long userID_;
    /**
     * <code>required int64 userID = 2;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    public boolean hasUserID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 userID = 2;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    public long getUserID() {
      return userID_;
    }

    // required int64 sessionID = 3;
    public static final int SESSIONID_FIELD_NUMBER = 3;
    private long sessionID_;
    /**
     * <code>required int64 sessionID = 3;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    public boolean hasSessionID() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 sessionID = 3;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    public long getSessionID() {
      return sessionID_;
    }

    private void initFields() {
      result_ = 0;
      userID_ = 0L;
      sessionID_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSessionID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, userID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, sessionID_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, userID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, sessionID_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static hc.login.PessCheck.LoginPessRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hc.login.PessCheck.LoginPessRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hc.login.PessCheck.LoginPessRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hc.login.PessCheck.LoginPessRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hc.login.PessCheck.LoginPessRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hc.login.PessCheck.LoginPessRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static hc.login.PessCheck.LoginPessRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static hc.login.PessCheck.LoginPessRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static hc.login.PessCheck.LoginPessRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hc.login.PessCheck.LoginPessRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(hc.login.PessCheck.LoginPessRsp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code login.LoginPessRsp}
     *
     * <pre>
     *13
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements hc.login.PessCheck.LoginPessRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hc.login.PessCheck.internal_static_login_LoginPessRsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hc.login.PessCheck.internal_static_login_LoginPessRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hc.login.PessCheck.LoginPessRsp.class, hc.login.PessCheck.LoginPessRsp.Builder.class);
      }

      // Construct using hc.login.PessCheck.LoginPessRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        userID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hc.login.PessCheck.internal_static_login_LoginPessRsp_descriptor;
      }

      public hc.login.PessCheck.LoginPessRsp getDefaultInstanceForType() {
        return hc.login.PessCheck.LoginPessRsp.getDefaultInstance();
      }

      public hc.login.PessCheck.LoginPessRsp build() {
        hc.login.PessCheck.LoginPessRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public hc.login.PessCheck.LoginPessRsp buildPartial() {
        hc.login.PessCheck.LoginPessRsp result = new hc.login.PessCheck.LoginPessRsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userID_ = userID_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sessionID_ = sessionID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hc.login.PessCheck.LoginPessRsp) {
          return mergeFrom((hc.login.PessCheck.LoginPessRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hc.login.PessCheck.LoginPessRsp other) {
        if (other == hc.login.PessCheck.LoginPessRsp.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasUserID()) {
          setUserID(other.getUserID());
        }
        if (other.hasSessionID()) {
          setSessionID(other.getSessionID());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        if (!hasUserID()) {
          
          return false;
        }
        if (!hasSessionID()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hc.login.PessCheck.LoginPessRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hc.login.PessCheck.LoginPessRsp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 result = 1;
      private int result_ ;
      /**
       * <code>required int32 result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 result = 1;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>required int32 result = 1;</code>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 result = 1;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }

      // required int64 userID = 2;
      private long userID_ ;
      /**
       * <code>required int64 userID = 2;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public boolean hasUserID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 userID = 2;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public long getUserID() {
        return userID_;
      }
      /**
       * <code>required int64 userID = 2;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public Builder setUserID(long value) {
        bitField0_ |= 0x00000002;
        userID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 userID = 2;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public Builder clearUserID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userID_ = 0L;
        onChanged();
        return this;
      }

      // required int64 sessionID = 3;
      private long sessionID_ ;
      /**
       * <code>required int64 sessionID = 3;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public boolean hasSessionID() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 sessionID = 3;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public long getSessionID() {
        return sessionID_;
      }
      /**
       * <code>required int64 sessionID = 3;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public Builder setSessionID(long value) {
        bitField0_ |= 0x00000004;
        sessionID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 sessionID = 3;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public Builder clearSessionID() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sessionID_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:login.LoginPessRsp)
    }

    static {
      defaultInstance = new LoginPessRsp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:login.LoginPessRsp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_login_LoginReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_login_LoginReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_login_LoginRsp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_login_LoginRsp_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_login_LoginPessReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_login_LoginPessReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_login_LoginPessRsp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_login_LoginPessRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013login.proto\022\005login\"\037\n\010LoginReq\022\023\n\013acco" +
      "untName\030\001 \002(\t\"*\n\010LoginRsp\022\016\n\006result\030\001 \002(" +
      "\005\022\016\n\006userID\030\002 \002(\003\"6\n\014LoginPessReq\022\023\n\013acc" +
      "ountName\030\001 \002(\t\022\021\n\tsessionID\030\002 \002(\003\"A\n\014Log" +
      "inPessRsp\022\016\n\006result\030\001 \002(\005\022\016\n\006userID\030\002 \002(" +
      "\003\022\021\n\tsessionID\030\003 \002(\003B\025\n\010hc.loginB\tPessCh" +
      "eck"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_login_LoginReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_login_LoginReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_login_LoginReq_descriptor,
              new java.lang.String[] { "AccountName", });
          internal_static_login_LoginRsp_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_login_LoginRsp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_login_LoginRsp_descriptor,
              new java.lang.String[] { "Result", "UserID", });
          internal_static_login_LoginPessReq_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_login_LoginPessReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_login_LoginPessReq_descriptor,
              new java.lang.String[] { "AccountName", "SessionID", });
          internal_static_login_LoginPessRsp_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_login_LoginPessRsp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_login_LoginPessRsp_descriptor,
              new java.lang.String[] { "Result", "UserID", "SessionID", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
